spring:
  application:
    name: order-service
   rabbitmq:
    host: 192.168.58.128
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2003/eureka,http://localhost:2002/eureka,http://localhost:2001/eureka
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
server:
  port: 8201
---
spring:  profiles: order2
server:
  port: 8202
