sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.58.128
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2003/eureka,http://localhost:2002/eureka,http://localhost:2001/eureka
  server:
    enable-self-preservation: false
---
spring:  profiles: user1
server:
  port: 8101
---
spring:  profiles: user2  
server:
  port: 8102